image:
  file: .gitpod.Dockerfile

tasks:
  - name: Installing prettier-plugin-latex
    command: npm i prettier-plugin-latex
  - name: LaTeX auto-rebuild
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
        latexmk -lualatex -pdf ; \
      done
  - name: Terminal

vscode:
  extensions:
    - efoerster.texlab
    - James-Yu.latex-workshop
    - JeffersonQin.latex-snippets-jeff
