image:
  file: .gitpod.Dockerfile

tasks:
  - name: Installing prettier-plugin-latex
    command: npm i prettier-plugin-latex
  # - name: LaTeX auto-rebuild latexmk
  #   command: >
  #     while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
  #       latexmk -lualatex -pdf ; \
  #     done
  - name: LaTeX auto-rebuild lualatex
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
        lualatex -interaction=nonstopmode -synctex=1 -halt-on-error -output-format=pdf main.tex ; \
      done



vscode:
  extensions:
    - efoerster.texlab
    - James-Yu.latex-workshop
    - JeffersonQin.latex-snippets-jeff
